const mongoose = require("mongoose");

const installmentSchema = new mongoose.Schema({
  installmentName: { type: String, required: true, trim: true },
  duePercent: { type: Number, default: 0 },
  dueAmount: { type: Number, default: 0 },
  dueDate: { type: Date, default: null },
  received: { type: Number, default: 0 },
  balance: { type: Number, default: 0 },
  status: { type: String, enum: ["Paid", "Partial", "Pending", "Overdue"], default: "Pending" }
}, { _id: true });

const transactionSchema = new mongoose.Schema({
  date: { type: Date, required: true },
  type: { type: String, required: true, trim: true },
  amount: { type: Number, required: true, default: 0 },
  paymentMode: { type: String, trim: true, default: "" },
  referenceNo: { type: String, trim: true, default: "" },
  remarks: { type: String, trim: true, default: "" }
}, { _id: true });

const bookingSchema = new mongoose.Schema({
  bookingId: { type: String, required: true, unique: true, trim: true, maxlength: 30 },
  project: { type: mongoose.Schema.Types.ObjectId, ref: "Project", required: true },
  unit: { type: mongoose.Schema.Types.ObjectId, ref: "Unit", required: true },
  newFlatNo: { type: String, trim: true, default: "" },
  configuration: { type: String, required: true, trim: true },
  carpetArea: { type: Number, default: 0 },
  carpetAreaUnit: { type: String, enum: ["Sq. Ft.", "Sq. M."], default: "Sq. Ft." },
  bookingDate: { type: Date, required: true },
  bookingStatus: { type: String, enum: ["Draft", "Booked", "Cancelled", "Hold", "Closed"], default: "Draft" },
  clientName: { type: String, required: true, trim: true },
  contactNumber: { type: String, required: true, trim: true },
  emailId: { type: String, trim: true, default: "" },
  clientLocation: { type: String, trim: true, default: "" },
  sanctionLetterReceived: { type: String, enum: ["Yes", "No"], default: "No" },
  bankName: { type: String, trim: true, default: "" },
  fundSource: { type: String, enum: ["Self", "Bank Loan", "Mixed", "Other"], default: "Self" },
  bankLoanPercentage: { type: Number, default: 0 },
  bookingSource: { type: String, enum: ["Direct", "Channel Partner", "Referral", "Digital Marketing", "Existing Customer", "Walk-in", "Other"], default: "Direct" },
  currentPSFStratum: { type: Number, default: 0 },
  currentPSFBaseRate: { type: Number, default: 0 },
  currentNetRate: { type: Number, default: 0 },
  currentAV: { type: Number, default: 0 },
  currentPossessionDevelopmentCharges: { type: Number, default: 0 },
  currentInternalAmenities: { type: Number, default: 0 },
  currentCarParkingAmount: { type: Number, default: 0 },
  bookingPSFStratum: { type: Number, default: 0 },
  bookingPSFBaseRate: { type: Number, default: 0 },
  bookingNetRate: { type: Number, default: 0 },
  bookingAV: { type: Number, default: 0 },
  bookingPossessionDevelopmentCharges: { type: Number, default: 0 },
  bookingInternalAmenities: { type: Number, default: 0 },
  bookingCarParkingAmount: { type: Number, default: 0 },
  bookingTotalNetAV: { type: Number, default: 0 },
  amountDuePercentage: { type: Number, default: 0 },
  amountDue: { type: Number, default: 0 },
  oldCollection: { type: Number, default: 0 },
  reraCollection: { type: Number, default: 0 },
  balance: { type: Number, default: 0 },
  receivedPercentage: { type: Number, default: 0 },
  dueDate: { type: Date, default: null },
  dpd: { type: Number, default: 0 },
  interest: { type: Number, default: 0 },
  disbursementDate: { type: Date, default: null },
  disbursementAmount: { type: Number, default: 0 },
  bankPayout: { type: Number, default: 0 },
  gstDue: { type: Number, default: 0 },
  gstReceived: { type: Number, default: 0 },
  gstPending: { type: Number, default: 0 },
  tdsApplicable: { type: Boolean, default: false },
  tdsDue: { type: Number, default: 0 },
  tdsReceived: { type: Number, default: 0 },
  tdsPending: { type: Number, default: 0 },
  sdrRegistrationPayment: { type: Number, default: 0 },
  scanningChargesDone: { type: Boolean, default: false },
  registrationRemarks: { type: String, trim: true, default: "" },
  registrationExpectedDate: { type: Date, default: null },
  registrationDate: { type: Date, default: null },
  registrationStatus: { type: String, enum: ["Not Started", "Documentation Pending", "Payment Pending", "Registration Scheduled", "Registered", "Cancelled"], default: "Not Started" },
  cpFirmName: { type: String, trim: true, default: "" },
  cpNameSourcingManager: { type: String, trim: true, default: "" },
  brokerage: { type: Number, default: 0 },
  cpPaid: { type: Number, default: 0 },
  cpDue: { type: Number, default: 0 },
  carParking: { type: Boolean, default: false },
  carParkingAmount: { type: Number, default: 0 },
  carParkingAmountReceived: { type: Number, default: 0 },
  dealNoteRemark: { type: String, trim: true, default: "" },
  installments: [installmentSchema],
  transactions: [transactionSchema],
  createdBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
  updatedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null }
}, { timestamps: true });

module.exports = mongoose.model("Booking", bookingSchema);
